### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by ebdavison** [AACEngineering/django-permissions-auditor#15]
We really need a way to export this to CSV so we can track this in our change management as well as share with auditor's who are asking for verification we have permissions applied.

**Comment by kluchrj** [comment]
I've added a `dump_view_permissions` management command in 1.2.0 which allows you to export the list to a csv or json file.

See the docs for details: https://django-permissions-auditor.readthedocs.io/en/latest/management_commands.html
